name: Run Tests

on:
  push:
    branches:
      - main  # Cambia "main" por el nombre de tu rama principal si es diferente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia la versión de Node.js según tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: name: Run Tests

on:
  push:
    branches:
      - main  # Cambia "main" por el nombre de tu rama principal si es diferente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia la versión de Node.js según tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

